blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/XeldarAlz/Vortex-SMS-Bomber/discussions
    about: Ask questions and discuss ideas with the community

